/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    resources: Resource;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    navigation: Navigation;
    footer: Footer;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Images and files — uploaded to Cloudflare R2
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for accessibility and SEO
   */
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Marketing pages built from reusable content blocks
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * The page title — appears in the browser tab and as the main heading
   */
  title: string;
  /**
   * URL path for this page (e.g. "features" becomes /features)
   */
  slug: string;
  /**
   * Add and arrange content blocks to build the page
   */
  layout?:
    | (
        | {
            /**
             * Main heading text — appears as the large H1
             */
            headline: string;
            /**
             * Supporting text below the headline
             */
            subheadline?: string | null;
            /**
             * Primary button text (e.g. "Get Started")
             */
            cta_label?: string | null;
            /**
             * Primary button link (e.g. "/test-drive")
             */
            cta_href?: string | null;
            /**
             * Optional hero image
             */
            image?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | FeatureAccordionBlock
        | {
            /**
             * Section heading above the pricing tiers
             */
            headline?: string | null;
            /**
             * Supporting text below the headline
             */
            subheadline?: string | null;
            /**
             * Features included in all plans — shown above the tier cards
             */
            included_features?:
              | {
                  feature: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Pricing tiers — typically 3 columns
             */
            tiers?:
              | {
                  /**
                   * Tier heading (e.g. "Up to 25 clusters")
                   */
                  tier_name: string;
                  /**
                   * Price display (e.g. "500.00" or "custom")
                   */
                  price: string;
                  /**
                   * Text after the price (e.g. "Per cluster* (monthly)")
                   */
                  price_suffix?: string | null;
                  /**
                   * Highlight this tier with a border accent
                   */
                  highlight?: boolean | null;
                  /**
                   * Button text (e.g. "Get Started" or "Talk to us")
                   */
                  cta_label?: string | null;
                  /**
                   * Button link (e.g. "/test-drive" or "mailto:letschat@caepe.sh")
                   */
                  cta_href?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Small print below the pricing tiers
             */
            footnote?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricingTable';
          }
        | CTAFormBlock
        | FeatureGridBlock
        | CardGridBlock
      )[]
    | null;
  meta?: {
    /**
     * SEO title — appears in search results (50-60 characters ideal)
     */
    meta_title?: string | null;
    /**
     * SEO description — appears below the title in search results (150-160 characters ideal)
     */
    meta_description?: string | null;
    /**
     * Social sharing image — shown when the page is shared on Twitter/LinkedIn (1200x630px)
     */
    og_image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureAccordionBlock".
 */
export interface FeatureAccordionBlock {
  /**
   * Eyebrow text above the section title (e.g. "Unique CAEPE Features")
   */
  section_label?: string | null;
  /**
   * Section heading (e.g. "Deployment", "Smoke Testing")
   */
  section_title: string;
  /**
   * Feature items within this accordion section
   */
  items?:
    | {
        /**
         * Feature name shown in bold
         */
        feature_name: string;
        /**
         * Feature description paragraph
         */
        feature_description: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureAccordion';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTAFormBlock".
 */
export interface CTAFormBlock {
  /**
   * Form section headline (e.g. "Request a Demo")
   */
  headline: string;
  /**
   * Supporting text below the headline
   */
  subheadline?: string | null;
  /**
   * Which form to display in this block
   */
  form_id: 'demo-request' | 'contact' | 'newsletter';
  /**
   * Optional additional content below the form
   */
  body_copy?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaForm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock".
 */
export interface FeatureGridBlock {
  /**
   * Small label above the headline (e.g. "Why CAEPE")
   */
  eyebrow?: string | null;
  /**
   * Section headline
   */
  headline?: string | null;
  items?:
    | {
        title: string;
        description: string;
        icon?:
          | (
              | 'star'
              | 'tachometer'
              | 'arrow-up-circle'
              | 'sitemap'
              | 'globe'
              | 'pointer'
              | 'briefcase'
              | 'users-cog'
              | 'deploy'
              | 'shield'
              | 'cube'
              | 'dollar'
              | 'rocket'
              | 'check'
              | 'clock'
              | 'code'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional CTA button text
   */
  cta_label?: string | null;
  /**
   * Optional CTA button link
   */
  cta_href?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardGridBlock".
 */
export interface CardGridBlock {
  /**
   * Small label above the headline
   */
  eyebrow?: string | null;
  /**
   * Section headline
   */
  headline?: string | null;
  cards?:
    | {
        title: string;
        description?: string | null;
        icon?:
          | ('star' | 'tachometer' | 'arrow-up-circle' | 'sitemap' | 'globe' | 'pointer' | 'briefcase' | 'users-cog')
          | null;
        id?: string | null;
      }[]
    | null;
  cta_label?: string | null;
  cta_href?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cardGrid';
}
/**
 * Articles, guides, and other resources
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: number;
  /**
   * Article title — appears as the main heading and in search results
   */
  title: string;
  /**
   * URL path for this article (e.g. "getting-started" becomes /resources/getting-started)
   */
  slug: string;
  /**
   * Short summary shown on the resources index page (max 250 characters)
   */
  excerpt?: string | null;
  /**
   * The full article body — use headings, lists, code blocks, and images
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Hero image shown at the top of the article and on resource cards
   */
  feature_image?: (number | null) | Media;
  /**
   * Author name displayed on the article
   */
  author?: string | null;
  /**
   * Publication date — articles are sorted by this date (newest first)
   */
  publish_date?: string | null;
  /**
   * Estimated reading time in minutes
   */
  reading_time?: number | null;
  /**
   * Tags for categorising this article — used for filtering on the resources page
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Related articles shown at the bottom of this article (select up to 3)
   */
  related_posts?: (number | Resource)[] | null;
  meta?: {
    /**
     * SEO title (50-60 characters ideal)
     */
    meta_title?: string | null;
    /**
     * SEO description (150-160 characters ideal)
     */
    meta_description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'resources';
        value: number | Resource;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              headline?: T;
              subheadline?: T;
              cta_label?: T;
              cta_href?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        featureAccordion?: T | FeatureAccordionBlockSelect<T>;
        pricingTable?:
          | T
          | {
              headline?: T;
              subheadline?: T;
              included_features?:
                | T
                | {
                    feature?: T;
                    id?: T;
                  };
              tiers?:
                | T
                | {
                    tier_name?: T;
                    price?: T;
                    price_suffix?: T;
                    highlight?: T;
                    cta_label?: T;
                    cta_href?: T;
                    id?: T;
                  };
              footnote?: T;
              id?: T;
              blockName?: T;
            };
        ctaForm?: T | CTAFormBlockSelect<T>;
        featureGrid?: T | FeatureGridBlockSelect<T>;
        cardGrid?: T | CardGridBlockSelect<T>;
      };
  meta?:
    | T
    | {
        meta_title?: T;
        meta_description?: T;
        og_image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureAccordionBlock_select".
 */
export interface FeatureAccordionBlockSelect<T extends boolean = true> {
  section_label?: T;
  section_title?: T;
  items?:
    | T
    | {
        feature_name?: T;
        feature_description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTAFormBlock_select".
 */
export interface CTAFormBlockSelect<T extends boolean = true> {
  headline?: T;
  subheadline?: T;
  form_id?: T;
  body_copy?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock_select".
 */
export interface FeatureGridBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  cta_label?: T;
  cta_href?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardGridBlock_select".
 */
export interface CardGridBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?: T;
  cards?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  cta_label?: T;
  cta_href?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  feature_image?: T;
  author?: T;
  publish_date?: T;
  reading_time?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  related_posts?: T;
  meta?:
    | T
    | {
        meta_title?: T;
        meta_description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Site-wide navigation bar — links and CTA button
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Navigation links shown in the header
   */
  nav_items?:
    | {
        /**
         * Link text shown in the nav bar
         */
        label: string;
        /**
         * URL path (e.g. "/features" or "https://external.com")
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * CTA button text (e.g. "Get Started")
   */
  cta_label?: string | null;
  /**
   * CTA button link (e.g. "/test-drive")
   */
  cta_href?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Site-wide footer — link groups and social media URLs
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Footer columns with grouped links
   */
  link_groups?:
    | {
        /**
         * Column heading (e.g. "Product", "Company")
         */
        group_label: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * GitHub profile URL
   */
  social_github?: string | null;
  /**
   * LinkedIn page URL
   */
  social_linkedin?: string | null;
  /**
   * X/Twitter profile URL
   */
  social_twitter?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  nav_items?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  cta_label?: T;
  cta_href?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  link_groups?:
    | T
    | {
        group_label?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  social_github?: T;
  social_linkedin?: T;
  social_twitter?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}